### ISSUE TITLE
Auto Export failures

### ISSUE THREAD

**Issue by devman16** [azmikemm/ZeoCompanion#9]
Auto export emails failing.

Error message as follows (sanitised):
```
ZeoCompanion CSV auto export
ZeoCompanion CSV auto export; see attachment.
/storage/emulated/0/Android/data/opensource.zeocompanion/outbox/ZeoCompanion_CSV_SS-myZeo-Minutes_2016-05-18-11-00-57_0_0_2.csv
Failed to send: IOException while sending message;
javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	javax.activation.UnsupportedDataTypeException: no object DCH for MIME type multipart/mixed; 
	boundary="----=_Part_5_371085498.1463581433144"
```

This error is encountered for both Image and CSV emails.

Refers to v1.0.3 Build 24 on Amazon Fire (5th Gen.)

**Comment by azmikemm** [comment]
Not able to replicate yet.  Some possible info at [StackOverflow](http://stackoverflow.com/questions/21856211/javax-activation-unsupporteddatatypeexception-no-object-dch-for-mime-type-multi#) and [StackOverflow](http://stackoverflow.com/questions/7521027/dch-class-error-with-javamail).

**Comment by devman16** [comment]
Yes, it does.

**Comment by devman16** [comment]
As far as I'm concerned, that's confirmed fixed.

Got a couple of emails this morning correctly dated and with viable attachment names.
